events {}

http {
    upstream backend {
        server app1:3000 max_fails=3 fail_timeout=10s;
        server app2:3001 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}