DROP TABLE IF EXISTS journal;

CREATE TABLE journal (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action VARCHAR(10) NOT NULL,
    user_name VARCHAR(255) NOT NULL
);