CREATE OR REPLACE FUNCTION calculate_age_valekzhanin(birth_date DATE)
RETURNS INTEGER
RETURNS NULL ON NULL INPUT
AS $$
    SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE, birth_date))::INTEGER;
$$ LANGUAGE SQL;