// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddField(arg1) {
  return window['go']['main']['App']['AddField'](arg1);
}

export function CreateCustomType(arg1) {
  return window['go']['main']['App']['CreateCustomType'](arg1);
}

export function DeleteField(arg1) {
  return window['go']['main']['App']['DeleteField'](arg1);
}

export function DropCustomType(arg1) {
  return window['go']['main']['App']['DropCustomType'](arg1);
}

export function ExecuteCustomQuery(arg1) {
  return window['go']['main']['App']['ExecuteCustomQuery'](arg1);
}

export function ExecuteJoinQuery(arg1) {
  return window['go']['main']['App']['ExecuteJoinQuery'](arg1);
}

export function GetCustomTypes() {
  return window['go']['main']['App']['GetCustomTypes']();
}

export function GetInsertFormFields(arg1) {
  return window['go']['main']['App']['GetInsertFormFields'](arg1);
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function GetTableNamesFromModels() {
  return window['go']['main']['App']['GetTableNamesFromModels']();
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function GetTablesMetadata() {
  return window['go']['main']['App']['GetTablesMetadata']();
}

export function InsertRecord(arg1) {
  return window['go']['main']['App']['InsertRecord'](arg1);
}

export function RecreateTables() {
  return window['go']['main']['App']['RecreateTables']();
}

export function RenameTable(arg1) {
  return window['go']['main']['App']['RenameTable'](arg1);
}

export function SearchInTable(arg1) {
  return window['go']['main']['App']['SearchInTable'](arg1);
}

export function UpdateCustomType(arg1) {
  return window['go']['main']['App']['UpdateCustomType'](arg1);
}

export function UpdateField(arg1) {
  return window['go']['main']['App']['UpdateField'](arg1);
}
