// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddField(arg1:main.AddFieldRequest):Promise<main.RecreateTablesResult>;

export function CreateCustomType(arg1:main.CreateCustomTypeRequest):Promise<main.RecreateTablesResult>;

export function DeleteField(arg1:main.DeleteFieldRequest):Promise<main.RecreateTablesResult>;

export function DropCustomType(arg1:main.DropCustomTypeRequest):Promise<main.RecreateTablesResult>;

export function ExecuteCustomQuery(arg1:main.CustomQueryRequest):Promise<main.TableDataResponse>;

export function ExecuteJoinQuery(arg1:main.JoinRequest):Promise<main.TableDataResponse>;

export function GetCustomTypes():Promise<main.CustomTypesListResponse>;

export function GetInsertFormFields(arg1:main.InsertRequest):Promise<Array<main.FieldInfo>>;

export function GetTableData(arg1:string):Promise<main.TableDataResponse>;

export function GetTableNamesFromModels():Promise<main.TablesListResponse>;

export function GetTableSchema(arg1:string):Promise<Array<main.FieldSchema>>;

export function GetTablesMetadata():Promise<Array<main.TableMetadata>>;

export function InsertRecord(arg1:main.InsertRecordRequest):Promise<main.RecreateTablesResult>;

export function RecreateTables():Promise<main.RecreateTablesResult>;

export function RenameTable(arg1:main.RenameTableRequest):Promise<main.RecreateTablesResult>;

export function SearchInTable(arg1:main.SearchRequest):Promise<main.TableDataResponse>;

export function UpdateCustomType(arg1:main.UpdateCustomTypeRequest):Promise<main.RecreateTablesResult>;

export function UpdateField(arg1:main.UpdateFieldRequest):Promise<main.RecreateTablesResult>;
